### ISSUE TITLE
how to set password?

### ISSUE THREAD

**Issue by ghost** [dizzus/RedisKit#1]
In the 'RedisKit' example project,I can't find any about set password
I search the function is follow 
`/*\* http://redis.io/commands/auth */
- (CocoaPromise*) auth: (id)password;`
  do it right?if right ,how to use it??
  TKS,TKS

**Comment by dizzus** [comment]
1. Have a look at AUTH command: http://redis.io/commands/AUTH
2. You should set your password in redis.conf, look for "requirepass" keyword.
3. Once connected to server your first command should be AUTH "yourpassword". Redis will reject any commands if your didn't authenticate correctly. Here's a little test case:

```
- (void)test_Auth {
    XCTestExpectation* test = [self expectationWithDescription: @"Auth connection test"];

    CocoaRedis* redis = [CocoaRedis new];
    [[[[redis connectWithHost: REDIS_ADDRESS] then:^id(id value) {
        return [[redis auth: @"s3cr3tz"] then:^id(id value) {
            return [redis ping];
        }];
    }] then:^id(id value) {
        XCTAssertEqualObjects(value, @"PONG");
        [test fulfill];
        return nil;
    }] catch:^id(NSError *err) {
        XCTFail(@"Failed");
        return nil;
    }];

    [self waitForExpectationsWithTimeout:2 handler:nil];
}

```

**Comment by ghost** [comment]
TKS! I use like this,it' s success!
`
    NSString *key = [NSString stringWithFormat:@"%@_%ld",[[NSDate date]dataWithFormat:@""],idd];
    CocoaRedis *redis = [CocoaRedis new];
    [[[[redis connectWithHost:kRediusDomain port:kRediusPort] then:^id(id value) {
        [redis auth:kRediusPassWord];
        NSArray* prams = @[@(1), @(10)];
        return [redis command: @[@"GET", key, prams]];
    }] then:^id(id value) {
        NSLog(@"Server version: %@", value);
        return nil;
    }] catch:^id(NSError *err) {
        NSLog(@"Error: %@", err);
        return nil;
    }];
`

**Comment by dizzus** [comment]
Ok. I think I'll add and example on how to use AUTH command.

**Comment by ghost** [comment]
best for you,TKS,I have anther question?
In my android project I use 'JRedis'，in this project I get the data from radius sever,I use the function

```
 jRedis.ping();
            System.out.println("** 连接聊天服务器成功，开始读取历史消息 **");
            String date = DateUtils.getStringDate(0);
            String id = "_" + MiniApp.curRoomId;
            String key = date + id;
            LogUtil.e("HistoryLise,key=" + key);
            List<byte[]> mList = jRedis.lrange(key, startIndex, endIndex);
```

the startIndex and the endIndex is the index page and page num of the response data
how can I set the startIndex and endIndex????
TKS,BEST FOR YOU!!

**Comment by ghost** [comment]
My android call 'jRedis' code section is blow!
My question is which function in 'RedisKit' like  jRedis.lrange(key, startIndex, endIndex);
is command?if is command,how can set startIndex and endIndex???
TKS!TKS

```
private void getHistoryMessages() {
    new Thread(() -> {
        try {
            jRedis.ping();
            System.out.println("** 连接聊天服务器成功，开始读取历史消息 **");
            String date = DateUtils.getStringDate(0);
            String id = "_" + MiniApp.curRoomId;
            String key = date + id;
            LogUtil.e("获取历史消息列表,key=" + key);
            List<byte[]> mList = jRedis.lrange(key, startIndex, endIndex);

            if (mList.size() > 0) {
                LogUtil.d("** 历史消息读取成功 size=" + mList.size() + " **");
                List<NgComingMsg> comingMsgList = new ArrayList<>();

                for (int i = mList.size() - 1; i >= 0; i--) {
                    byte[] bt = mList.get(i);
                    String msgStr = new String(bt);
                    comingMsgList.add(JSONObject.parseObject(msgStr, NgComingMsg.class));
                }

                Message msg = new Message();
                Bundle bd = new Bundle();
                bd.putSerializable("msg", (ArrayList) comingMsgList);
                msg.setData(bd);
                msg.what = 666;
                mHandler.sendMessage(msg);
                try {
                    XutilManager.getDbManager().replace(comingMsgList);
                } catch (DbException e) {
                    e.printStackTrace();
                }
            } else {
                LogUtil.e("** 历史消息列表为空 **");
                mHandler.sendEmptyMessage(0);
            }
            jRedis.quit();
        } catch (RedisException e) {
            e.printStackTrace();
        }
    }).start();
}
```

**Comment by dizzus** [comment]
You should check RedisKitTests out - there are tests for almost every Redis command. 
Here’s what you are looking for: 

https://github.com/dizzus/RedisKit/blob/master/RedisKitTests/ListsCommands.m#L291

Best regards.
